server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: EmployeeService
          uri: lb://EmployeeService
          predicates:
            - Path=/employee/**
        - id: DepartmentService
          uri: lb://DepartmentService
          predicates:
            - Path=/department/**
  config:
    import: "optional:configserver:http://localhost:8088"


